// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgnyhzemsemwwppsrvif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbnloemVtc2Vtd3dwcHNydmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MTUwOTAsImV4cCI6MjA5MDA5MTA5MH0.B9N4PSx3QbfPjcfhtJCuh6g1HUV942zMurBccRIhGc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});